version: '3.8'

services:
  app:
    build: .
    container_name: neoport-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - neoport_data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - neoport-network

  nginx:
    image: nginx:alpine
    container_name: neoport-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - neoport-network

volumes:
  neoport_data:


networks:
  neoport-network:
    driver: bridge
